### ISSUE TITLE
Supports are just a little bit too small to print reliably over many runs

### ISSUE THREAD

**Issue by nhendin** [hzeller/prusa-covid19-shield-remix#1]
I am finding that the supports on the v1.2 are just a little thin at the base to stay down reliably, some lift and others are fine. I've printed ~30 of the RC2 version of these parts without incident on this same printer / slicer settings and all were fine, but the first 2 of the v1.2's had problems. Note I didn't re-do the supports myself, I used the included ones.  Perhaps fatten them up at the base just a little, like a brim around the base of the crescent for 1-2 layers?

Note the good and failed support in this photo. 

![image](https://user-images.githubusercontent.com/3143787/77829767-6d2f7280-70e1-11ea-8a34-b471e632c131.png)

**Comment by hzeller** [comment]
Just updated that to have a little 'baseplate'. Can you verify that this works for you ?

**Comment by nhendin** [comment]
Henner,

Will check when this run of an RC2 is done. Thanks!  Sorry for the trouble.

--Neil.

**Comment by hzeller** [comment]
No worries, I am happy to work on making the process more robust for all circumstances.

**Comment by nhendin** [comment]
Updated version printed perfectly. Supports were well anchored to build plate but also easy to remove from model. Well done, and thanks for the quick turnaround.

Note I also cleaned and re-prepped the PEI sheet on my Prusa i3, which may also have helped, but I think the model is now much more robust to adhesion issues which is great.

Thank you!

**Comment by hzeller** [comment]
So in the first iteration, I've just added a solid layer as a 'foot', but I found that this was sticking *too* well on my printbed - while everything was already, that requires some manual scraping.

So I am considering changing it a little so that it is still larger, but not entirely filled.
![wider-foot](https://user-images.githubusercontent.com/140937/77838190-6d9e2c80-7126-11ea-81f7-4072a1144562.png)

Does this look reasonable ?

**Comment by hzeller** [comment]
(only slightly related: I notice you use the structured Prusa sheet; if you have, try the flat one, I found that that is usually much better in adherence for small structures)

**Comment by nhendin** [comment]
Interesting. I don't have the flat sheet unfortunately, but when they come
back online for parts orders, I will get one!

--Neil.

**Comment by nhendin** [comment]
I think that might work OK as well, I was able to get them off the textured
sheet easily, so perhaps it's a function of what sheet you have?  If you
want I can test it.  I have a git checkout of the repo from github so feel
free to push that (or on a branch and I'll run it after this job finishes).

I am currently printing another run of your footed support version and it's
working perfectly.

--Neil.

**Comment by hzeller** [comment]
I sent you the STL that only prints a column in the Prusa slack in that one thread; you can use that directly if you want.

**Comment by nhendin** [comment]
Just printed a grid of 20 of them at various points on the bed.  All well adhered to the textured PEI sheet on this printer:
![image](https://user-images.githubusercontent.com/3143787/77842896-743f9a80-714c-11ea-8dca-0fa66b61d6f3.png)

**Comment by hzeller** [comment]
Cool. So I'll continue with this one then.
