### ISSUE TITLE
Stack gap has consistent failure at inner band

### ISSUE THREAD

**Issue by titanous** [hzeller/prusa-covid19-shield-remix#13]
I've been trying to print "fast stacks" for the past few days using Coex PETG on a MK3S, and have the first level of parts printing reliably. However, when the second level starts printing, the first layer of the inner band (that touches the forehead) reliably does not "stick down" and sort of floats up a bit and messes up the print, eventually catching on the extruder after several layers.

My thinking is that a solution to that would be some tacks/columns in the gap layer spaced across the inner band that would provide a bit of plastic for the first layer of the next part to print properly. I'm not very good with Fusion 360 or OpenSCAD, so I was hoping that someone could make an STL with this mod and I could try it out. Thanks!

**Comment by hzeller** [comment]
Adding @esb7 who is working on the stacking.

**Comment by hzeller** [comment]
We were trying out some spacer things between the layers, but gave up on it as they were really hard to remove and created a rough surface ... which is not so good if it is something meant for sanitation.

**Comment by esb7** [comment]
We're using the same techinque / settings that prusa is using for their fast printing / stacks.  I wonder if just a very small bit of contact would work for this.  I think Prusa may have added a few very small circles in the gap layer.  I'll take a look at that tonight.  I've found that different filament behaves differently and you might need to increase or decrease the temperature to tune things.  I don't have a good feeling yet as to provide more concrete advice.  I've had an issue with at least one of the filaments I've been trying where the inner headband curve doesn't stick.  I suspect temp for that issue.  I'm not confident that only a small number of "attachment points" would resolve that.

**Comment by esb7** [comment]
Actually, upon rereading the original report, it sounds like the exact same problem I'm hitting.  Even if we add an anchor point around the start of the inner headband curve, I'm not sure if the rest will stick.  That definitely seems to be the area of greatest problem for me.  I have several other filaments that do not hit the issue with the same exact profile (other than calbrated extrusion width).

**Comment by titanous** [comment]
Thanks for the pointer! Turning the temperature back up to 265 fixed it! I had turned it down to 260 while working out some other issues and hadn't tried turning it back up yet.
