### ISSUE TITLE
Move Elastic tabs to align with top of frame and invert?

### ISSUE THREAD

**Issue by gunderson** [hzeller/prusa-covid19-shield-remix#22]
The current elastic band tabs can print at the current angle with few issues, but if they were moved up to align with the top surface it would give a nice flat plane to print. A good amount of the 45 degree wedge below could be removed in the process.

Has this been considered and rejected or are things moving fast enough that it hasn't been considered yet?

**Comment by hzeller** [comment]
Good question, this has not been considered yet, this is still from the original Prusa Design, where the front-pins where at the bottom. Now that the front-pins are in the middle and need support anyway, turning the band around for a band directly on the build-plate sounds indeed like a good idea.

It would not work for stacks though, as there we need the gradual built-up to avoid overhangs. Also there are now divots at the top for better stacking, these probably then should only enabled in the stacking version.

@gunderson can you try turning the STL around and do a test-print ? Given that this is PETG, this could mean that first-layer adhesion is _too good_ and will rip off the PEI sheet.

Paging @rrauenza and @esb7 : what do you think of this idea ?

**Comment by gunderson** [comment]
I'll print the change and report back

**Comment by esb7** [comment]
We'll probably need to get rid of the divot on that model to make it print properly.  As it is, at best you'll have a pretty large bridged area there.  I like the idea if it helps folks print easier or more consistently.  It will just be more models / variants to maintain.

**Comment by robertlacroix** [comment]
If we’d extend the holder in both directions so it aligns with top and bottom and make the surface area on the bottom a bit larger we’d only need one version, right? It would stack nicely actually and stick better on first layer, no need to print up side down.

**Comment by gunderson** [comment]
I spent some time in fusion 360 today after making the small change to invert and setting it to print.

First, the small change looks like it should be great, I had no trouble removing the petg from a buildtak surface at 80C. I understand the concern about the stackability of the current design. Perhaps the it should stay as is due to that.

Other changes I made:
- Added text and supports to the fusion 360 source file so the scad only needs to stack. Could also add stacking to fusion later.
- shrank the width of the extrusion so the headband can now be printed with 0% infill 3x perimeters on a 0.4mm nozzle. Should make the prints faster and more durable.
- [got rid of the divots](https://github.com/makernexus/prusa-covid19-shield-remix/issues/22#issuecomment-609095306) and cleaned up some corners


![IMG_1368](https://user-images.githubusercontent.com/2097146/78466369-3a731480-76b5-11ea-828f-f763acde61dc.jpg)
![IMG_1370](https://user-images.githubusercontent.com/2097146/78466371-3ba44180-76b5-11ea-87e8-f5b65ea2430b.jpg)
![IMG_1371](https://user-images.githubusercontent.com/2097146/78466373-3cd56e80-76b5-11ea-9823-67a2fa8ecada.jpg)
![IMG_1372](https://user-images.githubusercontent.com/2097146/78466374-3d6e0500-76b5-11ea-8abc-9431ef68853c.jpg)
![IMG_1373](https://user-images.githubusercontent.com/2097146/78466375-3e069b80-76b5-11ea-870f-2139e52ed661.jpg)
![IMG_1374](https://user-images.githubusercontent.com/2097146/78466376-3e9f3200-76b5-11ea-8772-e40cb995403b.jpg)


In the spirit of fulfilling demand, I also made a silicone-castable version of the headband with a 5-degree draft, molding pan and modular positive impression group w/ pin locators that should accommodate design updates. The current plan is to make a single silicon mold and cast w/ semi-rigid urethane resin to test. If it's successful, I may be able to 10x my own production speed from  a dozen headbands a day coming off the printer a day, to maybe 100 or coming out of molds. Pending validation of the design and tooling.

The mold system could probably be designed to facilitate stacked headbands.

![Prusa -  Adafruit - Nexus Mod Thin v17 castable](https://user-images.githubusercontent.com/2097146/78466298-70fc5f80-76b4-11ea-9104-0e0a51816a93.png)
![Prusa -  Adafruit - Nexus Mod Thin castable v17 positive](https://user-images.githubusercontent.com/2097146/78466300-7194f600-76b4-11ea-94eb-eda159d887c0.png)
![Prusa -  Adafruit - Nexus Mod Thin castrable v17 mold tray](https://user-images.githubusercontent.com/2097146/78466301-722d8c80-76b4-11ea-8398-8d314f7e7677.png)
![Prusa -  Adafruit - Nexus Mod Thin v1 7 castable](https://user-images.githubusercontent.com/2097146/78466302-72c62300-76b4-11ea-9b21-98ce4c0a1109.png)

I have some organization to do, then I'll submit a pull request tomorrow.

**Comment by gunderson** [comment]
Submitted and subsequently closed #23. Got some good feedback I'm going to address. Plans are in the comment chain.
https://github.com/makernexus/prusa-covid19-shield-remix/pull/23#issuecomment-609470870
